inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "**/*.erb" # Exclude ERB files from RuboCop checks

# Use double quotes for string literals as required by GitHub
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Use spaces inside array brackets
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space
