default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pass_safe_app_development

test:
  <<: *default
  database: pass_safe_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

  primary_replica:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    replica: true

cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cache:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

queue:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
